servers:
  # HTTP-based servers (external)
  weather:
    name: "Weather MCP Server"
    transport: "http"
    url: "https://mcp.pipedream.net/159d4d25-8d02-444d-972f-9671d4b6e55d/openweather_api"
    description: "Weather data and forecasts"
    enabled: true

  # STDIO-based servers (no ports needed!)
  calculator:
    name: "Calculator Server"
    transport: "stdio"
    command: "python3"
    args: ["src/simpli5/servers/calculator_server.py"]
    description: "Mathematical calculations and operations"
    enabled: true 
  
  meme:
    name: "Meme Generator"
    transport: "stdio"
    command: "npx"
    args: ["-y", "meme-mcp"]
    env:
      IMGFLIP_USERNAME: "AdarshTrivedi"
      IMGFLIP_PASSWORD: "lychee1234"
  
  job_agent:
    name: "Job Agent Server"
    transport: "stdio"
    command: "python3"
    args: ["src/simpli5/servers/job_agent_server.py"]
    description: "Job-related operations and message storage"
    enabled: true